### ISSUE TITLE
远程 Linux 服务器上调用此库会出现问题

### ISSUE THREAD

**Issue by Diving-Fish** [Astrian/mainetcn#4]
系统版本：Ubuntu 18.04
Node.js 版本：12.18.3
附带了 ult 和 token 的情况下，在我的 PC 上能够成功地从 https://maimai.wahlap.com/ 这个域名获取数据，但是在远程服务器上就出现了问题，报错和未提供 Cookie / Cookie 错误的情况一致（即 200002）。
下沉到 axios 进行测试，发现在 PC 上可以用 axios 请求到数据，但是在服务器上不行。
您对这个问题有没有头绪？

**Comment by Astrian** [comment]
你好，你的远程服务器八成是非中国大陆 IP。实测使用国际 IP（包括国际 VPS 或本地客户端使用大部分加速/代理服务等）会导致服务器报错。试试改用国内的 VPS 进行代理后使用 mainetcn，或者放弃在服务器端使用、改为用户请求后提交数据给服务器等方式解决。

**Comment by Astrian** [comment]
本问题由于是华立方面的隐形限制，且无法直接通过本包进行解决，故本 issue 将被关闭，有需要可继续评论并视情况重新开启。

~~顺便吐槽一句这破 API 要先抓包才能用真的不会有多少人能明白怎么用的… SEGA 什么时候能给开个正儿八经的 API 啊…🙄~~
